#端口号
debug: true
server:
  port: 8018
# 日志配置
logging:
  config: classpath:system/log4j2.xml
  level:
    org.springframework.boot.autoconfigure: ERROR
    com.fline: DEBUG
# Spring 相关配置
spring:
  jmx: 
    enabled: true
  redis:
    cluster:
      nodes:
      - '116.62.130.118:6379'
      - '116.62.130.118:6380'
      - '116.62.130.118:6381'
      - '116.62.130.118:6382'
      - '116.62.130.118:6383'
      - '116.62.130.118:6384'
    timeout: 0
    password: HKkNPyreV0aAtdP0Ec/3Gw==
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 50 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  kafka:
    bootstrap-servers: 47.110.224.137:9092
    consumer:
      group-id: fline88
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  profiles:
    include:
    - devdb
# 微服务的服务发现配置
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://172.16.21.53:28761/eureka/
#   instance:
#     prefer-ip-address: true

#daas:
#  apiservice:
#    url: http://172.16.1.223:9001/aic/rest/query
#    refreshsecreturl: http://172.16.1.223:9001/aic/rest/service/safety/refreshsecret
#    tenantusername: U0022Z0001
#    tenantpassword: 123456
#  fdmp:
#    db:
#      url: jdbc:mysql://172.16.23.199:3308/aic_trunk?serverTimezone=UTC
#      username: fline
#      password: flineCloud@2019root
